resource "local_file" "ansible_inventory" {
  filename = "${path.module}/k8s-ansible/inventory/hosts.ini"
  content = templatefile("${path.module}/templates/hosts.tpl", {
    lb_ip      = local.node_ips.k8s-lb.management
    master_ips = [for k, v in local.node_ips : v.management if startswith(k, "k8s-master")]
    worker_ips = [for k, v in local.node_ips : v.management if startswith(k, "k8s-worker")]
  })
}