---
- name: Add CRI-O repository
  apt_repository:
    repo: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ crio_version }}/xUbuntu_22.04/ /"
    state: present
    filename: "crio"

- name: Install CRI-O
  apt:
    name: ["cri-o", "cri-o-runc"]
    state: present

- name: Start CRI-O
  systemd:
    name: crio
    enabled: yes
    state: started